name: Example

on:
    - push

jobs:
  build:
    name: Build marc.pyz zipapp
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
            enable-cache: true
    
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      
      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Prepare app bundle
        run: |
            mkdir -p /tmp/out
            cp -r marc /tmp/out/marc
            uv export --no-hashes -o requirements.txt
            UV_LINK_MODE=copy uv pip install -r requirements.txt --target /tmp/out
            cp marc/__main__.py /tmp/out/__main__.py
    
      - name: Zipapp
        run: uv run python -m zipapp /tmp/out -p '/usr/bin/env python' -o marc.pyz --compress

      - uses: actions/upload-artifact@v4
        with:
          path: marc.pyz
  run:
    needs: build
    name: Run marc.pyz zipapp
    runs-on: ubuntu-latest
    steps:
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'
      - uses: actions/download-artifact@v4
        name: Download marc.pyz file
        with:
            path: .
      - name: Debug
        run: |
            ls -alh --color=auto . 
            ls -alh --color=auto */*
      - name: Run the app
        run: python marc.pyz migrate